### ISSUE TITLE
csv-plugin: pandas_opts

### ISSUE THREAD

**Issue by hoffmannmic** [SINTEF/dlite#108]
There is an issue with the pandas_opts option

if you execute something like 

`csvfile = thisdir / 'faithful.csv'`

`csv = dlite.Instance(f'csv:{csvfile}?'
                     'mode=r;'
                     'infer=False;'
                     'pandas_opts=decimal=",",thousands=".";'
                     'meta=http://meta.ifam.fraunhofer.de/0.1/Geyser')`

it works. 

If you add numerical options like "nrow=3" than it throws an error. The problem seems to be a type conversion issue or the lack of it. The pdopts come back as a dict from the regex-function "def optstring2keywords(optstring):". 

If you run it through some type conversion like

`pdopts = {k:int(v) for k,v in pdopts.items()}`

then it works. However not for mixed pandas option only for number options. It was just a test; could not think of something better. 

Secondly, I could not get any pandas_opts into the "save"-Instance part.

Something like 

`csv.save('csv:newfile.csv?pandas_opts=index=False')` 

I cannot get running.

I am not a python expert, but from my understanding the pandas_opts are set when the inst is created, and then used for read and save. Somehow not ideal. So I defined an option "pandas_out but I could not convince the function "def save"  to use it. Propably again a type conversion issue.

**Comment by jesper-friis** [comment]
Good point. I would like to avoid encode the type of all possible options that the pandas readers take. I therefore think the best solution is to use ast.literal_eval() (which in contrast to eval() is considered safe against malicious code injection). This changes the syntax of pandas_opts:

```python
csv.save('csv:newfile.h5?pandas_opts="key":"group", "index":False')
```
Looks ok?
