### ISSUE TITLE
DLITE_PYTHON_STORAGE_PLUGIN_DIRS: intended behaviour?

### ISSUE THREAD

**Issue by hoffmannmic** [SINTEF/dlite#110]
If DLITE_PYTHON_STORAGE_PLUGIN_DIRS is set to a local directory containing e.g. my-csv.py, a modified version of the csv-plugin

`thisdir = Path().parent`
`plugindir = thisdir / 'my-python-storage-plugins'`
`os.environ['DLITE_STORAGES'] = f'{thisdir}/entities/*.json'`
`os.environ['DLITE_PYTHON_STORAGE_PLUGIN_DIRS'] = str(plugindir)`
`import dlite` 

the plugins are ignored if the "same" plugin (here some csv-plugin) is in /usr/local/share/dlite/python-storage-plugins. I can see the reasoning, however if the user explicitly defines a local directory than it is unexpected that it is ignored.

**Comment by jesper-friis** [comment]
I agree. If you explicit define DLITE_PYTHON_STORAGE_PLUGIN_DIRS, you would expect it to override the default search path.
