### ISSUE TITLE
Bug: utils.py

### ISSUE THREAD

**Issue by hoffmannmic** [SINTEF/dlite#115]
There is a bug in the function "def instance_from_dict(d):" in the dlite/bindings/python/utils.py

The part
`try:`
`with dlite.silent:`
`return dlite.get_instance(d['uri'])`
`except dlite.DLiteError:`
`pass`

should checks whether the json file refered to in uri is available; otherwise the fallback part below is used and an instance from the dictionary is created. 

However if the file is not there the fallback part is not executed.

Something like 
`try:`
` with dlite.silent:`
` i = dlite.get_instance(d['uri'])`
` if i:`
` return i`
`except dlite.DLiteError:`
` pass`

fixes the problem.

**Comment by jesper-friis** [comment]
Thanks for the fixed. Pushed to PR #113
