### ISSUE TITLE
More semantic naming of plugin_path_delete() and similar functions

### ISSUE THREAD

**Issue by jesper-friis** [SINTEF/dlite#128]
Rename:
```
int plugin_path_delete(PluginInfo *info, int n)  -->  int plugin_path_delete_index(PluginInfo *info, int index)  

int plugin_path_remove(PluginInfo *info, const char *path) --> int plugin_path_delete(PluginInfo *info, const char *path)
```
Similar changes should be done in the following files:
* src/utils/plugin.c
* src/utils/fileutils.c
* src/dlite-mapping.c 
* src/dlite-storage.c
* src/dlite-mapping-plugins.c 
* src/dlite-storage-plugins.c

**Comment by Hridoy-31** [comment]
Hello @jesper-friis, can I work on this issue ? Thanks in advance. Have a good day !

**Comment by jesper-friis** [comment]
Of cause. You are very welcome to do that

**Comment by Hridoy-31** [comment]
Hello @jesper-friis, in which functions I have to do semantic naming in `src/dlite-mapping.c` file ? Can you please guide me through ? Have a nice day !

**Comment by jesper-friis** [comment]
You are right, there are no functions that should be renamed in `src/dlite-mapping.c`.

**Comment by jesper-friis** [comment]
Fixed
