### ISSUE TITLE
Add python tests suite for reading/writing different storage types and file formats

### ISSUE THREAD

**Issue by jesper-friis** [SINTEF/dlite#138]
Should also serve as a documentation.

**Comment by francescalb** [comment]
add to: bindings/python/tests/test_storage.py

e.g.: csv.meta.save('json:metadata.json')

**Comment by TorgeirUstad** [comment]
This test suite has been partially implemented in the branch 'Python test system for storages'. Tests for blobs and CSV files remain to be implemented.
