### ISSUE TITLE
Require cmake 3.16 to allow compiling dlite in debug mode on Windows

### ISSUE THREAD

**Issue by jesper-friis** [SINTEF/dlite#142]
By default Windows wants to link against the Python debug libraries when compiling dlite on windows. According to the stackoverflow post 
https://stackoverflow.com/questions/56798472/force-linking-against-python-release-library-in-debug-mode-in-windows-visual-stu
it is possible to change this default with

    set(Python_FIND_ABI "OFF" "ANY" "ANY")

which became available in [cmake 3.16](https://cmake.org/cmake/help/v3.16/module/FindPython.html). The post provides workarounds for older versions of cmake, but I think it is better to simply require cmake 3.16 and do it the simple way.

Ubuntu 20.04 comes with cmake 3.16.3, and Fedora 33 with cmake 3.19.7 so it should not cause any trouble for the build system.

**Comment by TorgeirUstad** [comment]
We already tried this and we didn't get it to work.

**Comment by jesper-friis** [comment]
Closing this one since the suggestion in the didn't worked
