### ISSUE TITLE
Building via CMake using the Ninja Generator fails with multiple rules for dlite.py

### ISSUE THREAD

**Issue by pscff** [SINTEF/dlite#144]
Steps to reproduce: Clone the repository, make a build directory and try to build using the Ninja generator.

```
$ mkdir out/build/ninja
$ cd out/build/ninja
$ cmake -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="Release" -DWITH_DOC=OFF -DWITH_HDF5=OFF -DALLOW_WARNINGS=ON ../../..
$ cmake --build . --config Release
ninja: error: build.ninja:4138: multiple rules generate bindings/python/dlite/dlite.py [-w dupbuild=err]
```

Tested on Windows and Ubuntu with Ninja 1.10.0
```
$ ninja --version
1.10.0
```

Not sure if this is a Ninja-issue or whether it is related to an undelying problem in the setup of the dlite-package. Using "Unix Makefiles" as Generator gracefully ignores the issue.

```
$ mkdir out/build/WSL-GCC-Release-makefiles
$ cd out/build/WSL-GCC-Release-makefiles
$ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING="Release" -DWITH_DOC=OFF -DWITH_HDF5=OFF -DALLOW_WARNINGS=ON ../../.. 
$ cmake --build . --config Release
$ ctest
```

**Comment by jesper-friis** [comment]
Were you able to use Ninja when you compiled dlite before summer?

**Comment by pscff** [comment]
No. I believe not, I switched to Makefiles directly.

**Comment by jesper-friis** [comment]
Should we close this issue?

DLite is now installable with `pip install dlite-python`, so the need for users to compile is strongly reduced.
