### ISSUE TITLE
Read collection from file

### ISSUE THREAD

**Issue by hoffmannmic** [SINTEF/dlite#164]
Based on the csv data set in the examples folder, I set up the following workflow: get csv data into dlite --> put data into a collection --> get data from the collection and do a calculation --> store result in the collection.

I can save the collection
coll3.save('json:newcollection.json')

Now I tried to re-read the collection via
coll_reread = dlite.Collection('json:newcollection.json?')

What I get is a new collection with "uri": "json:newcollection.json" but empty otherwise.

```
{
  "uuid": "a14a3d02-68fa-52a1-bb07-0f9dfc7781f9",
  "meta": "http://onto-ns.com/meta/0.1/Collection",
  "uri": "json:newcollection.json?",
  "dimensions": {
    "nrelations":  #0
  },
  "properties": {
    "relations": []
  }
}

```
Do I have to provide a metadata scheme how the collection looks like?

The dlite.collection docstrings says

```
Collection(storage, id, lazy=0)
    Loads collection with given `id` from `storage`. 
```

```
Collection(url, lazy)
    Loads collection from `url`, which should be of the form
    ``driver://location?options#id``.  
```

What is this id? What is the storage?

**Comment by jesper-friis** [comment]
Sorry for late answer. Running

```python
coll = dlite.Collection()
coll.save('json://coll.json')
```

will produce an empty collection as you describe

```json
{
  "0901b465-74a8-4b18-93d3-156de9ea0857":   {
    "meta": "http://onto-ns.com/meta/0.1/Collection",
    "dimensions": {
      "nrelations": 0
    },
    "properties": {
      "relations": []
    }
  }
}
```

You can easily view the collection schema with:
```python
print(coll.meta)
```
which will show that it has one dimension `nrelations` and one property `relations`. Hence, a collection is simply a set of relations. When you add an instance to a collection, you give it a local label and simply add a reference to it. You can also add relations between instances by referring to the local label. For example:
```python
coll.add('csv_label', csv)
coll.save('json://coll2.json')
```
will add three relations describing the new instance that was added (but I think we should update the predicate names, see #174)
```json
  "229fff52-ae30-4476-9999-9ce9e6097b1d":   {
    "meta": "http://onto-ns.com/meta/0.1/Collection",
    "dimensions": {
      "nrelations": 3
    },
    "properties": {
      "relations": [
         ["csv_label", "_is-a", "Instance"], 
         ["csv_label", "_has-uuid", "23fe9c0a-21e6-4ef5-a754-2a8e94b17a81"], 
         ["csv_label", "_has-meta", "onto-ns.com/meta/1.0/generated_from_csv_9019fa6ea45f0d868337c69406415882c7ce99793f61774b9463b212d7a080a6"]
      ]
    }
  }
```
Regarding your questions:
- You don't need to provide metadata when you add an instance to the collection.
- `id` is the id of the collection in the storage. It is either the uuid of the collection or (in case the collection was created with a human readable uri, like `coll = Collection('my-named-collection')`) its uri.
- A storage is a storage backend created with `dlite.Storage(driver, location, options='')`. The first argument specifies what storage plugin is used, like "json", "yaml", "postgresql", "rdf", "hdf5" etc. The url syntax is simply a shorthand that transparently opens a storage, reads from it and closes the storage again.

**Comment by jesper-friis** [comment]
@hoffmannmic, can we close this issue?

**Comment by hoffmannmic** [comment]
I have not have the time to work on the Dlite-workflow lately. It is on the plan for January.
