### ISSUE TITLE
pip installing from GitHub fails for Python3.9 on Windows

### ISSUE THREAD

**Issue by pscff** [SINTEF/dlite#209]
When pip installing from GitHub, i.e.

`pip install dlite-python@git+https://github.com/SINTEF/dlite.git@1d7b4ccec0e76799a25992534cd295a80d83878a#subdirectory=python`

an error is raised

**Comment by pscff** [comment]
Seems to be a Python 3.9 issue.

Workaround

- git clone dlite
- cd python
- python setup.py install

**Comment by CasperWA** [comment]
This should be made obsolete by #217.
