### ISSUE TITLE
Fix failing tests for Python wheel (musllinux, x86_64)

### ISSUE THREAD

**Issue by CasperWA** [SINTEF/dlite#225]
Everything builds correctly, however the test of the built wheel fails. The test being to install the wheel in a fresh virtual environment and running `python ./bindings/python/tests/test_python_bindings.py`.

**Comment by CasperWA** [comment]
This is still an issue, see [this job](https://github.com/SINTEF/dlite/runs/6090657631?check_suite_focus=true).

**Comment by jesper-friis** [comment]
Fixed in PR #217
