### ISSUE TITLE
do not Raise Error when instance not found while opening collection

### ISSUE THREAD

**Issue by sygout** [SINTEF/dlite#277]
When opening a collection of instances and one instance is not found, the code continues to run. 
It could be better that is stops there and raise an Error, even if the following message is displayed.

Message received:
** Error 1: cannot get instance "0ce026cc-289c-5b6a-af8c-eb99038d9265" labeled "http://www.ontotrans.eu/0.1/beamManufacturingDatum" from collection "90a76e1f-f71e-4a4e-9377-793b13cbf0a4".  Is DLITE_STORAGES properly set?

**Comment by jesper-friis** [comment]
I guess that this issue is about reading a collection from a storage (and not about a corrupted collection in memory)?

**Comment by jesper-friis** [comment]
Do you still have this issue after PR #293 has been merged to master?

**Comment by jesper-friis** [comment]
Closing since the issue was solved by PR #293
