### ISSUE TITLE
Add tests to the triplestore subpackage

### ISSUE THREAD

**Issue by jesper-friis** [SINTEF/dlite#341]
In order to make the triplestore package more independent, add a tests/ subdirectory and a requirements.txt file. 

Move the existing test_triplestore.py test from bindings/python/tests/ to the new tests/ directory. 

We could probably standardise on using pytest for this package. That will allow us to add standard fixtures that can be applied to all backends.

**Comment by francescalb** [comment]
Tests for all the functions in the triplestore must be implemented. Currently add_triples, remove, query, triples, remove, serialize and update do not have any tests.

**Comment by CasperWA** [comment]
As the `triplestore` sub-package has been made into a stand-alone package, this issue has no meaning here and can be closed.
