### ISSUE TITLE
Datamodel dimensions 

### ISSUE THREAD

**Issue by francescalb** [SINTEF/dlite#353]
When adding dimensions to the datamodel that are not used in the properties, no error is returned. 
This should not be valid. I suggest checking that all dimensions added are actually made use for, if not the datamodel should not contain it.

**Comment by jesper-friis** [comment]
I nice feature of DLite is that its C API is very fast. I am therefore not sure that we want to run such a check every time we load a metadata instance. 

Would it make sense to instead make a `dlite-validate` tool for validating instances and datamodels? The Python json loader has very good error reporting, so such a tool could also validate the json representation before validating its content.

**Comment by francescalb** [comment]
Making such a validation tool I think is a good suggestion.
