### ISSUE TITLE
Last character of fixstring not read

### ISSUE THREAD

**Issue by terence-coudert** [SINTEF/dlite#39]
I found an issue on fixstring type (maybe on the C side). If I define the person name (type string45) with exactly 45 characters, the last character is not read. When I stop the program where I convert the C char pointer into a fortran pointer, the fortran pointer contains 46 characters and the two last character are null.

**Comment by jesper-friis** [comment]
Thanks Terence. When and where does it happes and how can I reproduce it?

**Comment by terence-coudert** [comment]
I have only run the test_person program. It read a person in the persons.json storage and write the person in a new storage. I only modify the name of one person in persons.json file.

**Comment by terence-coudert** [comment]
I think I found the issue. If you remove the code line below in the function json-utils.c : dlite_json_get_value (case dliteFixString)

if (size > 0) ((char *)ptr)[size-1] = '\0';

Why do we have this code line? Could you double check? Then it seems also that there is no unit test on fix string type !?

**Comment by terence-coudert** [comment]
Fixed in commit [c1f26a9031fce](https://github.com/SINTEF/dlite/commit/c1f26a9031fce2d61efd3aa0080e617322b28747)
