### ISSUE TITLE
Duplicate object descriptions

### ISSUE THREAD

**Issue by CasperWA** [SINTEF/dlite#416]
Follow-up task from #415.

There are duplications in some methods or similar that are defined both in the C code and included Python files.
The resulting Sphinx warnings may also be due to overloaded functions, something that Sphinx and AutoAPI cannot handle.

**Comment by jesper-friis** [comment]
What methods are you referring to?

In general I think we want to use the same name in C and in the Python bindings for the same function (except that we in C prefix functions with `dlite_`).

**Comment by CasperWA** [comment]
From building the Sphinx documentation:

```shell
.../dlite/pydoc/autoapi/dlite/dlite/index.rst:1444: WARNING: duplicate object description of dlite.dlite.Instance.save, other instance in autoapi/dlite/dlite/index, use :noindex: for one of them
.../dlite/pydoc/autoapi/dlite/dlite/index.rst:1700: WARNING: duplicate object description of dlite.dlite.get_instance, other instance in autoapi/dlite/dlite/index, use :noindex: for one of them
.../dlite/pydoc/autoapi/dlite/index.rst:1490: WARNING: duplicate object description of dlite.Instance.save, other instance in autoapi/dlite/index, use :noindex: for one of them
```

And I indeed found the `get_instance()` function defined in both a C file as well as an included Python file, which extends a C file, supposedly?
As I don't fully understand these relationships concerning building the package, I am unsure exactly how to be more specific.
