### ISSUE TITLE
Have a proper pydantic -> dlite entity function

### ISSUE THREAD

**Issue by CasperWA** [SINTEF/dlite#501]
It would be straightforward to have a small utility function to generate DLite entities (data models) based off of pydantic models (classes) or instances.
The current functionality in `dlite.utils.to_metadata()` expects a pydantic instance and of a specific type as well, as the function passes on the `dict`-serialized pydantic instance to `dlite.utils.instance_from_dict()`, which expects the given `dict` to already have the correct data model structure.

**Comment by jesper-friis** [comment]
Do you have an example of a pydantic datamodel that you would like to generate an entity for?

**Comment by CasperWA** [comment]
This can be any data model.
For reference you could checkout the pydantic models in [OTEAPI Core (here the transformation config)](https://github.com/EMMC-ASBL/oteapi-core/blob/master/oteapi/models/transformationconfig.py) or in [OPTIMADE Python tools (here a replication of JSON:API v1)](https://github.com/Materials-Consortia/optimade-python-tools/blob/master/optimade/models/jsonapi.py).

**Comment by CasperWA** [comment]
Essentially, there are several ways to do this:

1. Go through the OpenAPI schema (a JSON file, which all pydantic models can generate).
2. Go through the Python API directly, using either pydantic classes or instances.
