### ISSUE TITLE
ImportError with pip-installed DLite

### ISSUE THREAD

**Issue by ajeklund** [SINTEF/dlite#519]
When running `import dlite`, the following error occurs:

```
>>> import dlite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<USER>/.local/lib/python3.10/site-packages/dlite.py", line 3, in <module>
    from . import mapping
ImportError: attempted relative import with no known parent package
>>>
```
DLite was installed using `pip install dlite`. This happens in both Windows and Linux (Ubuntu), and both inside and outside a python virtual environment.

**Comment by francescalb** [comment]
Dlite is not pip installable as `pip install dlite` but as `pip install DLite-Python`

**Comment by jesper-friis** [comment]
@ajeklund, ok to close this one?

**Comment by ajeklund** [comment]
Yes, `pip install DLite-Python` was indeed the solution.

The issue can be closed. Thank you!

**Comment by jesper-friis** [comment]
Closing
