### ISSUE TITLE
0.3.19 introduce error in ExecFlowDemo

### ISSUE THREAD

**Issue by francescalb** [SINTEF/dlite#534]
After latest release (0.3.19), the run.py in ExecFlowDemo fails.
https://github.com/H2020-OpenModel/ExecFlowDemo/tree/main/SDKdemo 

The error output is this, which is not very much.
python: /project/src/dlite-json.c:306: dlite_json_asprint: Assertion `0 <= m && m < (int)*size' failed.

**Comment by jesper-friis** [comment]
I am not able to reproduce this error with dlite corresponding to latest master installed on my system.

However, there is an i[ssue with the absolute](https://github.com/H2020-OpenModel/ExecFlowDemo/issues/27) for the `downloadUrl` in `SDKdemo/pipe.yaml`.

**Comment by francescalb** [comment]
OK
