### ISSUE TITLE
Cannot find NumPy include directories for Python 3.11 on Windows

### ISSUE THREAD

**Issue by jesper-friis** [SINTEF/dlite#553]
The dependabot-created PR #551 fails on Windows when upgrading actions/setup-python from v3 to v4.

It seems to be related to be related to that CMake cannot find include directories for NumPy: https://github.com/SINTEF/dlite/actions/runs/5308504398/jobs/9608057981?pr=551#step:6:198

@terence-coudert, can this related to the issue you have with pip-installing DLite on Windows?

**Comment by francescalb** [comment]
#551 has been fixed and merged
