### ISSUE TITLE
storages/python/python-storage-plugins/http.py needs requests

### ISSUE THREAD

**Issue by francescalb** [SINTEF/dlite#569]
Two errors:
requests is needed in requirements.

A test should be made for this plugin.

**Comment by jesper-friis** [comment]
Regarding requirements, I would prefer to add `requests` to a new `requirements_full.txt` file (see issue #517). 

A simple test using github is added in PR #593. The plugin was initially implemented to support the [entity-service](https://github.com/SINTEF/dlite-entities-service), but that seems never to get up and running...
