### ISSUE TITLE
DLite without `full` not working

### ISSUE THREAD

**Issue by CasperWA** [SINTEF/dlite#629]
Some dependencies (so far only `pint` has been spotted as the culprit) are still being imported by default in some repositories, making installations without the `full` dependency fail when using DLite.

**Comment by jesper-friis** [comment]
What do you mean with "DLite without full not working"? 

Tripper and pint are only needed for property mappings. Property mappings are only implemented in Python, and should be seen as an additional feature of DLite, rather than a basic feature. I added PR #648 to make it clear.

**Comment by CasperWA** [comment]
Meant as written. It installs an incomplete list of requirements compared to what is imported with "normal" use of DLite. Examples are given in the referencing issues from `oteapi-dlite` and `oteapi-optimade`. To make it easier I have here a link to the offending import lines in the `oteapi-optimade` tests: https://github.com/SINTEF/oteapi-optimade/actions/runs/5996062890/job/16259982128#step:5:1161

**Comment by CasperWA** [comment]
If there are modules in DLite with a public Python API that should not be used unless one has installed a specific extra set of dependencies, this should probably either be more clear when trying to use these modules, without having the dependencies installed, _or_ the modules should be made private.

**Comment by jesper-friis** [comment]
Property mappings are only implemented in Python and not part of the basic featureset of DLite available from the `dlite` namespace after an `import dlite`. To access property mappings, one has to explicit import them from `dlite.mappings`. PR #648 makes even more clear.

That said, the explicit import of pint you refer to above was removed a long time ago, when the generic parts of property mappings were refactored out from DLite to tripper. For some unknown reasons the refactored `bindings/python/mappings.py` file has been overwritten with its original content. The refactoring has been redone in PR #639, but that has not been reviewed yet...

**Comment by jesper-friis** [comment]
Closing this since there has been no response.

**Comment by CasperWA** [comment]
If #639 closes this issue, I would not close it pre-maturely?

**Comment by CasperWA** [comment]
For example. If one calls `dlite.Collection.get_instances(property_mappings=True)` this will fail, because it will call into `dlite.mappings` before checking if it can import `pint` and `tripper`.

This is an example I found quickly. But it is crucial all such cases are checked, verified, and taken care of.
The safest thing would be to state all top-level imports are hard requirements OR always check top-level imports in submodules and raise if they are not found with a message similar to the one found in the `get_instances()` method for `pint` and `tripper`.
This way one shouldn't have to make these checks within methods and functions either. It's a sample catch-'em-all if ever something is imported from a module that depends on (now) optional requirements.
