### ISSUE TITLE
hdf5 and swig no longer optional if python packages installed

### ISSUE THREAD

**Issue by francescalb** [SINTEF/dlite#710]
I installed all python pakages in the various reuirements*.txt files.
I did not have HDF5 or SWIG installed and this caused building from source to fail.
I guess it thinks hdf5 is installed since it finds the python package?

**Comment by jesper-friis** [comment]
HDF5 and SWIG are not python packages and should be installed with your package manager. See
https://sintef.github.io/dlite/getting_started/build/build_dependencies.html

SWIG is required for Python bindings. You can build DLite without Python bindings by configuring it with `cmake -DWITH_PYTHON=NO ...` 

HDF5 is required for the hdf5 storage plugin written in C. You can build DLite without HDF5 support by configuring it with `cmake -DWITH_HSF5=NO ...`

**Comment by jesper-friis** [comment]
Ok to close? 

Note that the DLite is compiled with HDF5 support when distributed to PyPI.
