### ISSUE TITLE
CI/CD fails when merging to master

### ISSUE THREAD

**Issue by jesper-friis** [SINTEF/dlite#790]
The github workflow triggered when merging to master fails. See https://github.com/SINTEF/dlite/actions/runs/7902227841

This seems to be related to the failing dependabot PR: https://github.com/SINTEF/dlite/pull/789

**Comment by CasperWA** [comment]
Use a PAT with the proper scope rights as can be seen here: https://github.com/SINTEF/dlite/actions/runs/7902227841/job/21605094026#step:7:35

**Comment by jesper-friis** [comment]
Fixed. Closing the issue
